export const PERMISSIONS = {
  // Company
  COMPANY_READ: "COMPANY_READ",
  COMPANY_UPDATE: "COMPANY_UPDATE",

  // Employee
  EMPLOYEE_CREATE: "EMPLOYEE_CREATE",
  EMPLOYEE_READ: "EMPLOYEE_READ",
  EMPLOYEE_UPDATE: "EMPLOYEE_UPDATE",
  EMPLOYEE_DELETE: "EMPLOYEE_DELETE",

  // Attendance
  ATTENDANCE_CREATE: "ATTENDANCE_CREATE",
  ATTENDANCE_READ: "ATTENDANCE_READ",
  ATTENDANCE_UPDATE: "ATTENDANCE_UPDATE",
  ATTENDANCE_DELETE: "ATTENDANCE_DELETE",
  ATTENDANCE_APPROVE: "ATTENDANCE_APPROVE",

  // Holiday
  HOLIDAY_CREATE: "HOLIDAY_CREATE",
  HOLIDAY_READ: "HOLIDAY_READ",
  HOLIDAY_UPDATE: "HOLIDAY_UPDATE",
  HOLIDAY_DELETE: "HOLIDAY_DELETE",

  // Leave
  LEAVE_CREATE: "LEAVE_CREATE",
  LEAVE_READ: "LEAVE_READ",
  LEAVE_UPDATE: "LEAVE_UPDATE",
  LEAVE_DELETE: "LEAVE_DELETE",
  LEAVE_APPROVE: "LEAVE_APPROVE",

  // Payroll
  PAYROLL_READ: "PAYROLL_READ",
  PAYROLL_CREATE: "PAYROLL_CREATE",
  PAYROLL_UPDATE: "PAYROLL_UPDATE",
  PAYROLL_PROCESS: "PAYROLL_PROCESS",

  // Expenses
  EXPENSE_CREATE: "EXPENSE_CREATE",
  EXPENSE_READ: "EXPENSE_READ",
  EXPENSE_UPDATE: "EXPENSE_UPDATE",
  EXPENSE_APPROVE: "EXPENSE_APPROVE",

  // Reports
  REPORT_READ: "REPORT_READ",

  // Organization
  ORGANIZATION_READ: "ORGANIZATION_READ",
  ORGANIZATION_MANAGE: "ORGANIZATION_MANAGE",

  // RBAC
  ROLE_READ: "ROLE_READ",
  ROLE_CREATE: "ROLE_CREATE",
  ROLE_UPDATE: "ROLE_UPDATE",
  ROLE_DELETE: "ROLE_DELETE",

  PERMISSION_READ: "PERMISSION_READ",
};
